import { Dashboard } from "./Dashboard";
import { Home } from "./Home";
import { Login } from "./Login";
import { Signup } from "./Signup";
import { Secret } from "./Secret";
import { Product } from "./Product";
import { CreateProduct } from "./CreateProduct";
import { NotFound } from "./NotFound";
import { Checkout } from "./Checkout";
export { Dashboard, Home, Login, Secret, Signup, Product, CreateProduct, NotFound, Checkout };
